services:
  - type: web
    name: phototribe-backend
    env: docker
    rootDir: backend
    plan: free
    dockerfilePath: ./Dockerfile
    envVars:
      - key: SPRING_PROFILES_ACTIVE
        value: dev
      - key: APP_CORS_ALLOWED_ORIGIN_PATTERNS
        value: https://your-netlify-site.netlify.app