spring.profiles.active=${SPRING_PROFILES_ACTIVE:dev}

spring.servlet.multipart.max-file-size=15MB
spring.servlet.multipart.max-request-size=20MB

photos.storage.location=uploads
photos.thumbnail.location=uploads/thumbnails

server.port=${SERVER_PORT:8080}
